// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATEStjXrhnMs0AdD1UGDSDPyA8FTqRoYU',
    appId: '1:868783400453:web:ff54dfc62d4b4da9701e6c',
    messagingSenderId: '868783400453',
    projectId: 'zc-dodiddone-53e4f',
    authDomain: 'zc-dodiddone-53e4f.firebaseapp.com',
    storageBucket: 'zc-dodiddone-53e4f.appspot.com',
    measurementId: 'G-LXHQXF8P6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDprsDOooWMD7StLAJT0mVld_X5buniuu8',
    appId: '1:868783400453:android:98d8eae65cd2fa21701e6c',
    messagingSenderId: '868783400453',
    projectId: 'zc-dodiddone-53e4f',
    storageBucket: 'zc-dodiddone-53e4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5RzdpIMe7_-e09_MKLH4OlIEQXd8uLHg',
    appId: '1:868783400453:ios:646c9e793365be13701e6c',
    messagingSenderId: '868783400453',
    projectId: 'zc-dodiddone-53e4f',
    storageBucket: 'zc-dodiddone-53e4f.appspot.com',
    iosBundleId: 'com.example.zcDodiddon',
  );
}
